# Generated by Django 5.2.5 on 2025-08-12 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='trees.menuitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'parent'), name='unique_displaysment')],
            },
        ),
    ]
